name: Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -f docker/Dockerfile-test -t fits-test .
      - name: Run tests
        run: docker run -v `pwd`:/fits:z -v ~/.m2:/root/.m2:z fits-test mvn clean test
